name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: devilkadabra69
          outputs: dist/snake.svg

      - name: Move to assets
        run: |
          mkdir -p assets
          cp dist/snake.svg assets/snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/snake.svg"
          message: "chore: update snake"
          default_author: github_actions
